### PR TITLE
Add Blender 4.2 LTS to defaults

### PR DESCRIPTION
**Pull request by BigRoy**
The Blender 4.2 LTS version has been released: https://www.blender.org/download/

image

So this updates the default settings to include it.

### Testing notes

1. Test whether Blender 4.2 works as intended

### CODE REVIEW

**Comment by BigRoy** [comment]
**Question:** Should we remove the Blender 2.9 versions from defaults?

**Comment by moonyuet** [comment]
> **Question:** Should we remove the Blender 2.9 versions from defaults?

Guess we should, I dont see the downloads in the website.

**Comment by BigRoy** [comment]
> **Question:** Should we remove the Blender 2.9 versions from defaults?

@m-u-r-p-h-y - your thoughts on this?

**Review by moonyuet — APPROVED** [review]
LGTM

**Pull request merged**
