### PR TITLE
Define WebActions

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
Applications addon does define web actions and adds new launch argument.

### Additional information
This PR requires
- AYON launcher 1.1.0 (https://github.com/ynput/ayon-launcher/pull/112)
- AYON core 0.4.4 (https://github.com/ynput/ayon-core/pull/781)
- AYON server 1.3.0 at least (https://github.com/ynput/ayon-backend/pull/183 & https://github.com/ynput/ayon-frontend/pull/563 )

This approach has few caveats. We always expected that launch of application happens from tray application where is possible to log into ftrack, kitsu etc. but with this approach they don't have option to login, we have to resolve that issue before full production.

### Testing notes
1. Make sure you have all requirements mentioned above.
2. Create package of applications addon.
3. Upload pacakge to server (upload is required).
4. Use it in a bundle.
5. If is used in developer bundle then make sure Develop mode is enabled and for production make sure Develop mode is disabled.
6. Select a task.
7. Applications actions should show up.
8. Launch any.

~~This PR might be split into 2 PRs, it does contain logic related to webactions and related to process preparation https://github.com/ynput/ayon-core/pull/781 .~~ They cannot be tested as separate PRs.

### CODE REVIEW

**Comment by fabiaserra** [comment]
Commented on https://github.com/ynput/ayon-launcher/pull/112#issuecomment-2318075788

**Comment by fabiaserra** [comment]
It's working great for me, I only encountered that blocker from my last comment and it also broke our CI/CD pipeline to upload addons to the server due to:
```python
Traceback (most recent call last):
  File "__startup__.py", line 120, in run
  File "console.py", line 16, in run
  File "start.py", line 981, in <module>
  File "start.py", line 971, in main
  File "start.py", line 671, in boot
  File "start.py", line 657, in init_launcher_executable
  File "/pipe/ayon/release/current/common/ayon_common/utils.py", line 940, in deploy_ayon_launcher_shims
    _deploy_shim_linux(installer_shim_root)
  File "/pipe/ayon/release/current/common/ayon_common/utils.py", line [83](https://gitlab.alkemy-x.com/coreweave/pipeline/ayon/ayon-applications/-/jobs/70541#L83)9, in _deploy_shim_linux
    with open(dst_desktop_executable, "r") as stream:
NotADirectoryError: [Errno 20] Not a directory: '/root/.local/share/applications/ayon.desktop'
Extracting /pipe/ayon/release/current/shim/shim.tar.gz -> /root/.local/share/AYON/shim
```

**Comment by iLLiCiTiT** [comment]
> It's working great for me, I only encountered that blocker from my last comment and it also broke our CI/CD pipeline to upload addons to the server due to:

Not related to this PR. And sorry, because we won't change it. Any comments related to this please move to ayon-launcher.

**Review by 64qam — APPROVED** [review]
works on Windows

**Comment by 64qam** [comment]
Doesn't work on linux. Applications show up, but even launcher doesn't start:-(

**Review by 64qam — APPROVED** [review]

**Comment by iLLiCiTiT** [comment]
> Doesn't work on linux. Applications show up, but even launcher doesn't start:-(

Resolved, it was on linux that was used for testing of previous versions and had shim variant from development phase.

**Pull request merged**
